### ISSUE TITLE
Define the runtime interface output by CSS loader and make it "public"

### ISSUE THREAD

**Issue by jquense** [webpack-contrib/css-loader#1042]
hey @evilebottnawi 👋 While building a few loaders i was struck by how so much of the css webpack ecosystem is dependent on the output of css-loader. There is this implicit export API that css-loader uses that is consumed but style-loader and extraction plugins. For others to build versions of those it depends on knowing css-loaders runtime output.

It seems like i'd be a good idea to define the output interface e.g. `exports` of css-loader processed modules and consider any change to it a "breaking change". This isn't really in response to anything, just thinking about how we can add more stability to this integral piece of web tech! I'd be happy to write up a API spec that describes the current output and any tests (tho css-loader is well tests already so not sure there are any missing)

**Comment by evilebottnawi** [comment]
Yes, let's do it, feel free to create a new section in readme and documented that. You can investigate how it is work looking at the tests.

**Comment by evilebottnawi** [comment]
After thinking, I thought that we should not document this, it will require detailed explanations that it will be difficult for most to understand, any changes in the API is breaking change and should be done under major release (except new features), so public API is using semver, you can rely on it, anyway if you still want to do it PR welcome. I want to close the issue because it will most likely never be done
