### ISSUE TITLE
Webpack alias false on directories / expressions

### ISSUE THREAD

**Issue by mmarton** [webpack-contrib/css-loader#1317]
Related to https://github.com/webpack-contrib/css-loader/issues/1291
Aliasing individual files to false to prevent resolving works fine for individual files. But unfortunately not for directories / expressions

- Operating System: linux mint 20
- Node Version: 15.11
- NPM Version: 7.6 (but I use yarn: 1.22.5)
- webpack Version: 5.38.1
- css-loader Version: 5.2.6

### Expected Behavior

According to the webpack doc I could alias directories or regular expressions to someting.
https://webpack.js.org/configuration/resolve/#resolvealias

{ xyz: 'modu/dir' } | /abc/node_modules/modu/dir/index.js | /abc/node_modules/modu/dir/file.js
-- | -- | --
{ xyz$: 'modu/dir' } | /abc/node_modules/modu/dir/index.js | /abc/node_modules/xyz/file.js

Aliasing these to false doesn't work with css-loader

### Code

```js
const path = require('path');
module.exports = {
    entry: './index.css',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'build.css'
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: {loader: 'css-loader'}
            }
        ]
    },
    resolve: {
        alias: {'/assets/': false}
    }
}```

```css
.logo {
    background-image: url(/assets/logo.png);
}
```

**Comment by alexander-akait** [comment]
Expected, `/assets/logo.png` is not module, `/assets/` will not work with JS too

**Comment by mmarton** [comment]
:( ok, is it good as a feature request or sould i close it?

**Comment by alexander-akait** [comment]
Give me minute I will look at this

**Comment by alexander-akait** [comment]
Oh I see, here the same problem (https://github.com/webpack-contrib/css-loader/issues/1246, description is different, but internally problem only here), we need major release for this (we are already working on it), right now I recommend to use https://github.com/webpack-contrib/css-loader#function

But here note - `resolve.alias` will not work here, because it works on with explicit module, but you want to ignore whole directory, but we have other plugin:
```
new webpack.IgnorePlugin({ resourceRegExp: /\/assets\// })
```

but it will work only after we fix https://github.com/webpack-contrib/css-loader/issues/1246

So let's close in favor https://github.com/webpack-contrib/css-loader/issues/1246

I think we will do major release in near future (maybe the next week or next week after the next week :smile: )

**Comment by mmarton** [comment]
That's exactly what I want to do. I have a (symlinked) static folder under the docroot that I don't want to be processed (and duplicated in the build folder by webpack)  
The callback works I'll go with `config.url = url => !url.startsWith('/static/');` until this will be released.

tanks for the help.
