### ISSUE TITLE
Module string is formatted differently in externals function when required via composition

### ISSUE THREAD

**Issue by dbow** [webpack-contrib/css-loader#220]
I'm trying to generate a bundle to use for prerendering server-side, so I'm using `css-loader/locals` to only export the classnames, as recommended [here](https://github.com/webpack/css-loader#local-scope):

> Note: For prerendering with extract-text-webpack-plugin you should use css-loader/locals instead of style-loader!css-loader in the prerendering bundle. It doesn't embed CSS but only exports the identifier mappings.

The config for the server bundle includes this CSS loader:
webpack.config.js

```
      {
        test: /\.css/,
        exclude: /node_modules/,
        loader: 'css-loader/locals?modules&localIdentName=[name]__[local]___[hash:base64:5]',
      },
```

It works fine when importing CSS files into the JS components, but it does not seem to handle composition within CSS files.

For example, calling `import styles from './list.css';` with the following two files:
**list.css**

```
.link {
  composes: orange-text from './colors.css';
}
```

**colors.css**

```
.orange-text {
  color: orange;
}
```

generates the following in the output bundle:

```
/***/ },
/* 11 */
/***/ function(module, exports, __webpack_require__) {

    module.exports = {
        "link": "list__link___35xGm " + __webpack_require__(12)["orange-text"] + ""
    };

/***/ },
/* 12 */
/***/ function(module, exports) {

    module.exports = require("-!./../../../node_modules/css-loader/locals.js?modules&localIdentName=[name]__[local]___[hash:base64:5]!./colors.css");

/***/ },
```

It looks like the list.css file is correctly mapping to a classname ("list__link___35xGm") but the composition is generating a `require` statement that cannot be resolved ("require("-!./../../../node_modules/css-loader/locals.js?modules&localIdentName=[name]**[local]_**[hash:base64:5]!./colors.css")")?

When I try to run the server with that bundle, I get an import error:
`Error: Cannot find module '-!./../../../node_modules/css-loader/locals.js?modules&localIdentName=[name]__[local]___[hash:base64:5]!./colors.css'`

**Comment by dbow** [comment]
I realized this was actually a problem with my `externals` function:

```
  externals: function(context, request, callback) {
    if (request.indexOf('src') !== 0 &&
        request.indexOf('.') !== 0) {
      return callback(null, 'commonjs ' + request);
    }
    callback();
  },
```

I was trying to treat anything that was not a relative import and didn't begin with `src` as external. But the `request` param for the composition calls ends up being that long string `"-!./../../../node_modules/css-loader/locals.js?modules&localIdentName=[name]__[local]___[hash:base64:5]!./colors.css"`, which caused them to be treated as external.

I guess that seems a little non-intuitive that the same type of string (e.g. `./colors.css` vs. `./list.css`) will be formatted differently in the externals function based on whether it's `require`d vs. imported via composition? Not sure if this is viewed as a problem!

**Comment by agilgur5** [comment]
Had the same problem when I was importing CSS modules (via `loader: 'style-loader!css-loader?modules'`) -- although the path I had was relative to a directory `./...`, the path after bundle + export was something like `!./../../../node_modules/css-loader/...`.

My externals is set to everything that's non-relative (so all NPM packages aren't bundled, but my source code is) with a simple regex:
`externals: /^[^.]/`, which failed on CSS modules because of this bug, so I had to change it to:
`externals: /^[^.!]/` to include the `!`, after which it worked.

Based on the data from @dbow and I, it would seem like anything loaded with a query on the loader causes the `require` path to be formatted differently. Might be a general problem with webpack loader queries, not just limited to `css-loader`

**Comment by pixelass** [comment]
related to #537

**Comment by pixelass** [comment]
has anyone ever figured this out? 

I need to generate a JSON with mappings but I need the classnames instead of a require statement.
Seems like a very generic feature that is simply not supported.

If I knew how this works I could resolve the require statement with a new loader. But there is just Zero documentation. All I find is issues considering this output format.

**Comment by evilebottnawi** [comment]
Problem still exists?

**Comment by pixelass** [comment]
@evilebottnawi I don't use this mechanism anymore. I think I figured it out somehow and AFAIR it was a problem in my implementation.

**Comment by evilebottnawi** [comment]
Let's close this issue. If somebody will face this problem feel free to feedback.
