### ISSUE TITLE
Code needs linting + new contributors

### ISSUE THREAD

**Issue by mgcrea** [webpack-contrib/css-loader#251]
I just checked out the code and it's a mess! Mixed spaces and tabs, etc. You should have a standard eslint file for every projects under the `webpack` namespace. Usually, [airbnb styleguide](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) is a good start. You could extend it in a new project `eslint-config-webpack` and apply that strictly to all projects.

I know you must have more on your plate right now. I'll gladly help if you want. With 94 pending issues and 7 PRs, I think it's time to add new collaborators.

**Comment by bebraw** [comment]
I poked Tobias about this. Hopefully we get you on board. :+1:

I agree a linting standard would be great (easier PRs, development). https://github.com/webpack/css-loader/issues/124 is probably the highest priority item. After 0.14x *css-loader* lost a significant chunk of performance. This was due to the inclusion of postcss based processing and CSS Modules supoprt if I remember correctly.

Perhaps the best way to fix that would be to revert back to 0.14 state, apply possible fixes on top of that where possible, and encourage people to use CSS Modules through postcss (postcss-loader). It's a special case after all.

**Comment by bebraw** [comment]
@mgcrea Any update? As far as I understand, Tobias should have contacted you by now. 😄

**Comment by mgcrea** [comment]
@bebraw Indeed, I've been added as a contributor for the webpack CSS related projects, but I have been pretty busy lately. #124 does not look like an easy fix, will try to dig a little bit deeper in the coming days/weeks. Hope I'll be able to help.

**Comment by bebraw** [comment]
@mgcrea Ok, cool. #124 seems active so that's good!

**Comment by jhnns** [comment]
👍 for creating a webpack eslint
👍 for keeping the css-loader simple. I think, @sokra justed wanted to add some features and ended up with CSS modules – which is cool, but many projects just want the css-loader to resolve urls and translate it into CommonJS. It's not fair to put the performance overhead on those :)

**Comment by michael-ciniawsky** [comment]
@mgcrea `v1.0.0` will have all of that 😛
