### ISSUE TITLE
Does css-loader check for naming collisions

### ISSUE THREAD

**Issue by danilobuerger** [webpack-contrib/css-loader#273]
Does css-loader using `localIdentName` with (as an example) `localIdentName=_[hash:base64:5]` check for naming collisions?

**Comment by hurrtz** [comment]
That I'd like to know, too. For instance in production mode I'd like to use as few characters in the hash as possible to reduce size of the generated stylesheet. So far I guess I'm ok with base64:3 which would allow for around 262k classnames. I guess for the first few thousand classnames I am quite save but eventually the chance for collision should increase if there are no counter measures.

**Comment by danilobuerger** [comment]
@hurrtz don't expect an answer though ;) i am looking for one since May.

**Comment by lili21** [comment]
almost 2 years ?

**Comment by evilebottnawi** [comment]
@lili21 because it is out of scope `css-loader`, we use https://github.com/css-modules/postcss-modules and their modules to transform css modules code to css. This issue should be created in their repos instead here. Sorry but we can't do here anything. Thanks everyone for issue, please re create issue in their repo(s).
