### ISSUE TITLE
Specifying minimize options for cssnano

### ISSUE THREAD

**Issue by dkrutsko** [webpack-contrib/css-loader#414]
I believe there is a **bug** in the way that cssnano options are currently being passed into css-loader. According to the documentation it specifies that they should be loaded like so:

```js
{
  test: /\.css$/,
  use: [
    {
      loader: 'css-loader',
      options: {
        minimize: true || {/* CSSNano Options */}
      }
    }
  ]
}
```

However, looking at the [source code](https://github.com/webpack-contrib/css-loader/blob/master/lib/processCss.js#L181-L188) and testing it myself revealed that they actually have to be attached to the options object directly:

```js
{
  test: /\.css$/,
  use: [
    {
      loader: 'css-loader',
      options: {
        /* CSSNano Options */
      }
    }
  ]
}
```

Should that code be `query.minimize`? or should the documentation be updated?

**Comment by Ashoat** [comment]
I had the very same thought when reading the documentation, but after considering the innate ridiculousness of the expression `true || {/* CSSNano Options */}` (due to JavaScript's short-circuit evaluation of boolean expressions) I figured that the documenter must've been using the `||` as a shorthand for "or". I agree that this is confusing; in my opinion, "/* or */" would be clearer.

**Comment by oleksiibilous** [comment]
@dkrutsko You are right. `minimize: true || {/* CSSNano Options */}`looks like both `true` or object with configurations must be assigned to  `minimize` key and any of them will enable minimization. However, it will only work, if `minimize: true` is set. Moreover, now all params from `options` are being passed to css nano configuration, which is not a good idea, because of potential issues with keys' duplication

There is even a [pull request](https://github.com/webpack-contrib/css-loader/pull/400), which implements the fix. I hope it will be accepted & merged soon

**Comment by michael-ciniawsky** [comment]
Discussion and Feedback please moved to #400 Thx you guys 😛
