### ISSUE TITLE
NPM audit - Critical Command Injection

### ISSUE THREAD

**Issue by MichaelFBA** [webpack-contrib/css-loader#716]
Because of a deep dependancy `macaddress` it is advised not to use this plugin.

```
Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ css-loader [dev]                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ css-loader > cssnano > postcss-filter-plugins > uniqid >     │
│               │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/654
```

**Comment by TomS-** [comment]
Noticed this, is there an alternative until this is fixed?

**Comment by MichaelFBA** [comment]
Looks like it might be getting fixed downstream.

**Comment by evilebottnawi** [comment]
@MichaelFBA need help with release `cssnano@4`

**Comment by evilebottnawi** [comment]
https://github.com/ben-eb/cssnano/milestone/6

**Comment by mickael-kerjean** [comment]
Same here but this issue is a symptom of a much deeper problem: why would a dependency of a dependency of a dependency of a dependency of a plugin that manage CSS in a build system would need to know about my mac address in the first place?

The randomid version of the Leftpad syndrom? Lack of third party dependency audit? It doesn't feel right.

**Comment by TomS-** [comment]
@mickael-kerjean I was thinking exactly that, why does it need to know my mac-address?

**Comment by mickael-kerjean** [comment]
@JamesCodes : The question isn't what it does but why did this land here in the first place. You can generate a unique id in 1 line of code:
``` javascript
function uniqid(){ return (Math.random()*Math.pow(10,18)).toString(16) }
```

**Comment by JamesCodes** [comment]
@michael-ciniawsky completely agree, it's not needed. Looks like a fix may be close: https://github.com/postcss/postcss-filter-plugins/pull/18

**Comment by evilebottnawi** [comment]
Guys i am contributor and maintainer `cssnano`, feel free to send PR, don't have time right, go ahead :+1:

**Comment by JamesCodes** [comment]
I've fixed the linting issues on the PR that replaces the vulnerable dependancy: https://github.com/postcss/postcss-filter-plugins/pull/19

Just need to get it merged in and update the relevant dependent repos.

**Comment by JamesCodes** [comment]
@evilebottnawi I have managed to get a fix merged into `postcss-filter-plugins` and have created an update to the tagged version of [cssnano](https://github.com/JamesCodes/cssnano/tree/css-nano-3.10.0-fixed), but I am a bit confused about how I can get that into the branch

**Comment by evilebottnawi** [comment]
@JamesCodes just update you deps and lock file (`cssnano@3` already use `^` for this plugin https://github.com/ben-eb/cssnano/blob/v3.10.0/package.json#L40)

**Comment by JamesCodes** [comment]
@evilebottnawi You will have to excuse my ignorance, but I don't quite understand. My project is dependant on `cssnano`. Is it not possible for me to contribute to that package with the fix?

**Comment by evilebottnawi** [comment]
@JamesCodes `cssnano@3` already have fixed version of plugin (just update your deps and lock file), `cssnano@4-rc` doesn't use this module and all works file.

**Comment by JamesCodes** [comment]
@evilebottnawi I'm with you now! Thank you very much.

**Comment by kumorig** [comment]
So, since I'm not all that good with npm/github, I must ask: Do you consider this fixed now? How do you even handle this in your projects? 

Do you fork css-loader, change deps, use your own fork and hope you don't forget about it (like what if there are more critical vulnerabilities found later, do I even get a notice if I use my own github-fork?)   

Or do you edit your package-lock file, update cssnano versions everywhere and never use `npm install again`?

Or do you use npm shrinkwrap? I've tried that all day long and I've only lost all my changes to npm-shrinkwrap.json like 4 times because I apparently have no clue of what I'm doing...

Is there some sane way to handle audit vulnerabilities in sub-dependencies?  (sorry, I realize this doesn't belong here, but I might as well...  (until they fix the dependency and bump up the version)

**Comment by KyloJorgensen** [comment]
Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           
                                                                                
                                                                                
  critical        Command Injection                                             
                                                                                
  Package         macaddress                                                    
                                                                                
  Dependency of   css-loader                                                    
                                                                                
  Path            css-loader > cssnano > postcss-filter-plugins > uniqid >      
                  macaddress                                                    
                                                                                
  More info       https://nodesecurity.io/advisories/654                        


npm audit
version 6+

when are we going to resolve this audit?

**Comment by bdiz** [comment]
What is the npm command for getting the dependency updated? I've tried many things but nothing has worked for me.

**Comment by Hypnosphi** [comment]
@evilebottnawi unfortunately, `postcss-filter-plugins` has this fixed only in v3, which isn't covered by `^2.0.0` range

**Comment by KyloJorgensen** [comment]
@dbiz 
npm update the-name-of-the-dependency

**Comment by JasonFritsche** [comment]
Is it safe to use this on a local server?

**Comment by evilebottnawi** [comment]
Just update your deps and lock files (run `npm/yarn install`) and all

**Comment by rettgerst** [comment]
I don't think this issue is resolved yet.

the issue is fixed upstream in postcss-filter-plugins version 3.0.1. this package depends on cssnano ^3.10.0, which itself depends on postcss-filter-plugins ^2.0.0. the caret means npm will _not_ install postcss-filter-plugins higher than 2.x.x, so nuking node_modules, or running `npm upgrade` still leaves me with postcss-filter-plugins 2.0.2.

I created a [pull request](https://github.com/postcss/postcss-filter-plugins/pull/21) that ports the fixes from postcss-filter-plugins v3 back to their v2, so if/when they merge and publish, this will no longer effect css-loader.

**Comment by evilebottnawi** [comment]
@rettgerst yep, you are right, `cssnano@3` use `postcss-filter-plugins@2`, need backport, we can't update this in `cssnano@3` due backward compatibility :disappointed:

**Comment by magnusriga** [comment]
@evilebottnawi 

I am confused about this. The problem is not solved on my end.

I installed cssnano@next (4.0.0-rc.2), deleted node_modules and lock files, and re-installed npm as advised.

The problem is still that css-loader depends on cssnano@3.10.0. So whenever I install css-loader, the old cssnano is automatically installed (next to cssnano@next) and used as the dependency.

I need to somehow force css-loader to instead use cssnano@next as its dependency.

How is that done?

Thank you.

**Comment by evilebottnawi** [comment]
@magnusriga because `css-loader` use `cssnano@3`, i wrote about this above. Need solve this issue https://github.com/ben-eb/cssnano/projects/1, PR welcome, right now i am one who support `cssnano` with `2m` downloads, i don't have time on all (i maintain `prettier/stylelint/webpack/webpack-contrib/cssnano/etc` also i have regular work), i need you help.

Also after fix cssnano issues we can update `postcss` to 6 version and get perf

**Comment by rettgerst** [comment]
postcss-filter-plugins merged my PR and released 2.0.3, but I don't [see it on npm yet](https://www.npmjs.com/package/postcss-filter-plugins). whenever 2.0.3 shows up on npm, new installs will use 2.0.3 and the issue will be resolved here and anything else downstream of postcss-filter-plugins v2. neither this package nor anything else upstream need any more maintenance to fix this issue.

**Comment by magnusriga** [comment]
@ahester57 How can it be avoided? I was only able to remove the vulnerability by removing css-loader completely from the project?

Do we not have to just update the dependency css-loader uses? Move it from cssnano@latest to cssnano@next (which has fixed the issue)?

**Comment by evilebottnawi** [comment]
@magnusriga move to `cssnano@next` it breaking changes, also `cssnano@next` is not fully complete.

**Comment by magnusriga** [comment]
@rettgerst Sorry to beat a dead hores (and for the naive question), but is the problem here not that css-loader uses cssnano@3.10.0 instead of 4.0.0-rc.2? I was under the impression that cssnano@4.0.0-rc.2 had removed its dependency on postcss-filter-plugins v2.

If that is correct, is not all that is needed to update what dependency css-loader uses (from cssnano@3.10.0 to cssnano@4.0.0-rc.2)?

**Comment by evilebottnawi** [comment]
Guys stop spamming, it is bug tracker, please use https://gitter.im/webpack/webpack for communication, also i avaliable here if somebody have question I will reply within 24 hours within business days.

Right now we triangle how we can move `css` as build-in part of webpack. But i agree we need update `css-loader` before we do this.

Problem with vulnerable dep already fixed and release in `postcss-filter-plugins`, right now `npm` has some problems on server, just wait they will solve and update you lock files.

**Comment by jspencersharpe** [comment]
Seems like npm's server problems are resolved because deleting node_modules and package-lock didn't fix the critical vulnerability yesterday but fixes it today. Thanks @evilebottnawi.
